version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: oms-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    # KHONG MO PORT KHI LEN MOI TRUONG THAT
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
        timeout: 20s
        retries: 10
    networks: [ oms-network ]
  oms-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${BACKEND_IMAGE}
    container_name: oms-backend
    env_file:
      - ".env"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
    ports:
      - "${APP_PORT}:8080"
    expose:
      - "8080"
    depends_on:
      - mysql
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks: [ oms-network ]

volumes:
  mysql_data:

networks:
  oms-network:
    driver: bridge